### PR TITLE
flash.sh: bootstrap ssh and wpa_supplicant files

### PR DESCRIPTION
**Pull request by danbst**

### CODE REVIEW

**Review by andrewyazura — CHANGES_REQUESTED** [review]
1. On WSL closes immediately. (Problem is that on line 34, variable SEPARATE_WINDOW isn't being created)
2. Hash of OS is **always** different from the one that is downloaded

**Comment by danbst** [comment]
@andrew4ever I hope first issue is solved. As for the second issue, I can't reproduce. 

But we found with @scrapmecanic3000 that `curl` often fails because of network problems, so I've looped `curl` until it downloads whole file. It may be one of the reasons why downloaded data hash isn't matched.

**Review by andrewyazura — CHANGES_REQUESTED** [review]
sha256sum returns such hash: "41235examplehash344213 *filename", while we need "41235examplehash344213 filename". To remove asterisk before filename add `-t` on line 49.

It should be:
`filehash="$(sha256sum -t $OS_NAME)"`.

Also, drive name isn't passed to separate window.

**Comment by andrewyazura** [comment]
Oh, I forgot to comment out `set -x` on line 4.

**Review by andrewyazura — CHANGES_REQUESTED** [review]
`bootstrap_ssh_part1()` isn't working. mount can't find temp directory.

[Screenshot](https://imgur.com/a/Bkjyd44)

**Comment by danbst** [comment]
@andrew4ever removed that. Also, arguments should be passed fine now to git-bash, so I reverted your explicit `$drive` passthrough.

Please, confirm it works for you.

**Comment by andrewyazura** [comment]
> 
> 
> @andrew4ever removed that. Also, arguments should be passed fine now to git-bash, so I reverted your explicit `$drive` passthrough.
> 
> Please, confirm it works for you.

Your changes fixed those issues, thanks. But bug in `bootstrap_ssh_part1()` still exists

**Review by andrewyazura — APPROVED** [review]
Everything is fine and works perfectly well!

**Pull request merged**
